# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /ajay/src/app

# Copy the current directory contents into the container
COPY package*.json ./

# Install the app dependencies
RUN npm install

# Bundle app source
COPY . .

# The app runs on port 3000
EXPOSE 3000

# Define the command to run the app
CMD ["node", "app.js"]
